# Generated by Django 4.0.7 on 2022-11-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0002_alter_mantenances_piecesechangees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenances',
            name='piecesEchangees',
        ),
    ]
