# Generated by Django 4.0.6 on 2022-11-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieVehicules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=60, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['intitule', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Chauffeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=20)),
                ('salaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom', 'prenom', 'salaire'],
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(blank=True, max_length=250, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DepenseMissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('intitule', models.CharField(choices=[('frais de carburant', 'frais de carburant'), ('frais de voyage', 'frais de voyage'), ('frais de douane', 'frais de douane')], max_length=250, unique=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='docsTransports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(choices=[('visite technique', 'visite technique'), ('assurance', 'assurance')], max_length=250)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
            ],
            options={
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='InfoDepenseMissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoDepenseMission', to='exercices.exercices')),
                ('intitule_depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_cout', to='missions.depensemissions')),
            ],
            options={
                'ordering': ['intitule_depense'],
            },
        ),
        migrations.CreateModel(
            name='LoueurVehicules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250, null=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mission', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etat_mission', models.BooleanField(default=False)),
                ('motif', models.CharField(choices=[('Approvissionement', 'Approvissionement'), ('Livraison', 'Livraison')], default='Approvissionement', max_length=250)),
                ('exercice_conerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_missions', to='exercices.exercices')),
                ('liste_depenses', models.ManyToManyField(through='missions.InfoDepenseMissions', to='missions.depensemissions')),
            ],
            options={
                'ordering': ['-date_mission'],
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('unite', models.CharField(choices=[('Kg', 'kilogramme'), ('tonne', 'tonne'), ('tube', 'tube')], default='Kg', max_length=25)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Trajets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(choices=[('Ouaga', 'Ouagadougou'), ('Bobo', 'Bobo Dioulasso'), ('Bamako', 'Bamako'), ('Accra', 'Accra')], default='Bobo', max_length=50)),
                ('ville_arrivee', models.CharField(choices=[('Ouaga', 'Ouagadougou'), ('Bobo', 'Bobo Dioulasso'), ('Bamako', 'Bamako'), ('Accra', 'Accra')], default='Bobo', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Vehicules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immat', models.CharField(max_length=250, unique=True)),
                ('marque', models.CharField(max_length=60, null=True)),
                ('couleur', models.CharField(max_length=60, null=True)),
                ('est_disponible', models.BooleanField(default=True)),
                ('poids_vide', models.DecimalField(decimal_places=7, max_digits=10)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='missions.categorievehicules')),
            ],
            options={
                'ordering': ['immat'],
            },
        ),
        migrations.CreateModel(
            name='documentVehicules',
            fields=[
                ('docstransports_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='missions.docstransports')),
            ],
            bases=('missions.docstransports',),
        ),
        migrations.CreateModel(
            name='VehiculeParcs',
            fields=[
                ('vehicules_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='missions.vehicules')),
            ],
            bases=('missions.vehicules',),
        ),
        migrations.CreateModel(
            name='Recettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_unitaire', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('qte_produit', models.PositiveIntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_recette', to='missions.clients')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoRecetteMission', to='exercices.exercices')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_recette', to='missions.missions')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_recette', to='missions.produits')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RecetteDetailSansPesage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos_snsPesee', to='missions.recettes')),
            ],
            options={
                'ordering': ['-id_recette'],
            },
        ),
        migrations.CreateModel(
            name='RecetteDetailPesage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premier_pese', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('deuxieme_pese', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos_pesee', to='missions.missions')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='missions',
            name='liste_produits',
            field=models.ManyToManyField(related_name='liste_produits', through='missions.Recettes', to='missions.produits'),
        ),
        migrations.AddField(
            model_name='missions',
            name='trajet_concerne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liste_missions', to='missions.trajets'),
        ),
        migrations.AddField(
            model_name='missions',
            name='vehicule_concerne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_missions', to='missions.vehicules'),
        ),
        migrations.AddField(
            model_name='infodepensemissions',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_depenses', to='missions.missions'),
        ),
        migrations.CreateModel(
            name='VehiculeLoues',
            fields=[
                ('vehicules_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='missions.vehicules')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='missions.loueurvehicules')),
            ],
            bases=('missions.vehicules',),
        ),
        migrations.AddConstraint(
            model_name='recettes',
            constraint=models.UniqueConstraint(fields=('produit', 'mission', 'client_concerne'), name='unique_recette_key'),
        ),
        migrations.AddField(
            model_name='documentvehicules',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos_documents', to='missions.vehiculeparcs'),
        ),
        migrations.AddField(
            model_name='chauffeurs',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur', to='missions.vehiculeparcs'),
        ),
    ]
