# Generated by Django 4.0.7 on 2022-12-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_docstransports_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infodepensemissions',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recettedetailpesage',
            name='deuxieme_pese',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recettedetailpesage',
            name='premier_pese',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recettes',
            name='cout_unitaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicules',
            name='poids_vide',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
